import React from 'react';
import './globals.css';

export const metadata = {
  title: 'Tubban Multi-Tenant Platform',
  description: 'Bespoke business websites dynamically generated by AI.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className="antialiased">{children}</body>
    </html>
  );
}
