import React from 'react';
import './globals.css';

export const metadata = {
  title: 'Swiss LeadGen Admin & Multi-Tenant Platform',
  description: 'Bespoke business websites dynamically generated by AI in Switzerland.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head>
        {/* 全局 Tailwind CSS 载入防护，确保 100% 精美展现 */}
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className="antialiased bg-slate-950 text-slate-100">{children}</body>
    </html>
  );
}
